import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  English: {
    // Sidebar
    "Dashboard": "Dashboard",
    "Upload Contracts": "Upload Contracts",
    "Analysis Results": "Analysis Results",
    "Reports": "Reports",
    "Saved Reports": "Saved Reports",
    "Risk Overview": "Risk Overview",
    "Clause Explorer": "Clause Explorer",
    "Settings": "Settings",
    "Logout": "Logout",
    "AI Legal Assistant": "AI Legal Assistant",
    "Ask questions about your contracts and get AI insights.": "Ask questions about your contracts and get AI insights.",
    "Go to Assistant": "Go to Assistant",

    // Settings Page
    "Profile Information": "Profile Information",
    "Your Name": "Your Name",
    "Full Name": "Full Name",
    "Email Address": "Email Address",
    "Phone Number": "Phone Number",
    "Company": "Company",
    "Role": "Role",
    "Bio": "Bio",
    "Save Changes": "Save Changes",
    "Appearance": "Appearance",
    "Theme": "Theme",
    "Light": "Light",
    "Dark": "Dark",
    "System": "System",
    "Primary Color": "Primary Color",
    "Your data is secure": "Your data is secure",
    "All data is encrypted and stored securely.": "All data is encrypted and stored securely.",
    "Change Password": "Change Password",
    "Current Password": "Current Password",
    "New Password": "New Password",
    "Confirm Password": "Confirm Password",
    "Update Password": "Update Password",
    "Language & Region": "Language & Region",
    "Language": "Language",
    "Date Format": "Date Format",
    "Time Zone": "Time Zone",
    "Save Preferences": "Save Preferences",
    "AI & Analysis": "AI & Analysis",
    "Analysis Mode": "Analysis Mode",
    "Contradiction Strictness": "Contradiction Strictness",
    "Save Settings": "Save Settings",
    "Email Notifications": "Email Notifications",
    "Save Notifications": "Save Notifications",
    "Manage your account, preferences and application settings.": "Manage your account, preferences and application settings.",
    "Analysis Completed": "Analysis Completed",
    "Receive email when analysis is completed": "Receive email when analysis is completed",
    "Risk Alerts": "Risk Alerts",
    "Receive email for high risk issues": "Receive email for high risk issues",
    "Report Generated": "Report Generated",
    "Receive email when reports are generated": "Receive email when reports are generated",
    "System Updates": "System Updates",
    "Important updates and announcements": "Important updates and announcements"
  },
  Tamil: {
    // Sidebar
    "Dashboard": "முகப்பு (Dashboard)",
    "Upload Contracts": "ஒப்பந்தங்களை பதிவேற்று (Upload Contracts)",
    "Analysis Results": "பகுப்பாய்வு முடிவுகள் (Analysis Results)",
    "Reports": "அறிக்கைகள் (Reports)",
    "Saved Reports": "சேமித்த அறிக்கைகள் (Saved Reports)",
    "Risk Overview": "ஆபத்து கண்ணோட்டம் (Risk Overview)",
    "Clause Explorer": "விதிமுறைகள் தேடல் (Clause Explorer)",
    "Settings": "அமைப்புகள் (Settings)",
    "Logout": "வெளியேறு (Logout)",
    "AI Legal Assistant": "AI சட்ட உதவியாளர்",
    "Ask questions about your contracts and get AI insights.": "உங்கள் ஒப்பந்தங்கள் பற்றிய கேள்விகளைக் கேட்டு AI நுண்ணறிவுகளைப் பெறுங்கள்.",
    "Go to Assistant": "உதவியாளரிடம் செல்",

    // Settings Page
    "Profile Information": "சுயவிவரத் தகவல்",
    "Your Name": "உங்கள் பெயர்",
    "Full Name": "முழுப் பெயர்",
    "Email Address": "மின்னஞ்சல் முகவரி",
    "Phone Number": "தொலைபேசி எண்",
    "Company": "நிறுவனம்",
    "Role": "பங்கு (Role)",
    "Bio": "பயோ (Bio)",
    "Save Changes": "மாற்றங்களைச் சேமி",
    "Appearance": "தோற்றம் (Appearance)",
    "Theme": "தீம் (Theme)",
    "Light": "வெளிச்சம்",
    "Dark": "இருட்டு",
    "System": "கணினி",
    "Primary Color": "முதன்மை நிறம்",
    "Your data is secure": "உங்கள் தரவு பாதுகாப்பானது",
    "All data is encrypted and stored securely.": "அனைத்து தரவுகளும் குறியாக்கம் செய்யப்பட்டு பாதுகாப்பாக சேமிக்கப்படுகின்றன.",
    "Change Password": "கடவுச்சொல்லை மாற்று",
    "Current Password": "தற்போதைய கடவுச்சொல்",
    "New Password": "புதிய கடவுச்சொல்",
    "Confirm Password": "கடவுச்சொல்லை உறுதிப்படுத்து",
    "Update Password": "புதுப்பி",
    "Language & Region": "மொழி மற்றும் பகுதி",
    "Language": "மொழி",
    "Date Format": "தேதி வடிவம்",
    "Time Zone": "நேர மண்டலம்",
    "Save Preferences": "விருப்பங்களைச் சேமி",
    "AI & Analysis": "AI & பகுப்பாய்வு",
    "Analysis Mode": "பகுப்பாய்வு முறை",
    "Contradiction Strictness": "முரண்பாடு கடுமை (Strictness)",
    "Save Settings": "அமைப்புகளைச் சேமி",
    "Email Notifications": "மின்னஞ்சல் அறிவிப்புகள்",
    "Save Notifications": "அறிவிப்புகளைச் சேமி",
    "Manage your account, preferences and application settings.": "உங்கள் கணக்கு, விருப்பங்கள் மற்றும் பயன்பாட்டு அமைப்புகளை நிர்வகிக்கவும்.",
    "Analysis Completed": "பகுப்பாய்வு முடிந்தது",
    "Receive email when analysis is completed": "பகுப்பாய்வு முடிந்ததும் மின்னஞ்சல் பெறவும்",
    "Risk Alerts": "ஆபத்து எச்சரிக்கைகள்",
    "Receive email for high risk issues": "அதிக ஆபத்து சிக்கல்களுக்கு மின்னஞ்சல் பெறவும்",
    "Report Generated": "அறிக்கை உருவாக்கப்பட்டது",
    "Receive email when reports are generated": "அறிக்கைகள் உருவாக்கப்படும் போது மின்னஞ்சல் பெறவும்",
    "System Updates": "கணினி புதுப்பிப்புகள்",
    "Important updates and announcements": "முக்கிய புதுப்பிப்புகள் மற்றும் அறிவிப்புகள்"
  },
  Hindi: {
    "Dashboard": "डैशबोर्ड",
    "Upload Contracts": "अनुबंध अपलोड करें",
    "Analysis Results": "विश्लेषण परिणाम",
    "Reports": "रिपोर्ट",
    "Saved Reports": "सहेजी गई रिपोर्ट",
    "Risk Overview": "जोखिम अवलोकन",
    "Clause Explorer": "खंड एक्सप्लोरर",
    "Settings": "सेटिंग्स",
    "Logout": "लॉग आउट",
    "AI Legal Assistant": "AI कानूनी सहायक",
    "Ask questions about your contracts and get AI insights.": "अपने अनुबंधों के बारे में प्रश्न पूछें और AI अंतर्दृष्टि प्राप्त करें।",
    "Go to Assistant": "सहायक के पास जाएं",
    "Profile Information": "प्रोफ़ाइल जानकारी",
    "Your Name": "आपका नाम",
    "Full Name": "पूरा नाम",
    "Email Address": "ईमेल पता",
    "Phone Number": "फ़ोन नंबर",
    "Company": "कंपनी",
    "Role": "भूमिका",
    "Bio": "परिचय",
    "Save Changes": "परिवर्तन सहेजें",
    "Appearance": "दिखावट",
    "Theme": "थीम",
    "Light": "हल्का",
    "Dark": "गहरा",
    "System": "सिस्टम",
    "Primary Color": "प्राथमिक रंग",
    "Your data is secure": "आपका डेटा सुरक्षित है",
    "All data is encrypted and stored securely.": "सभी डेटा एन्क्रिप्टेड और सुरक्षित रूप से संग्रहीत हैं।",
    "Change Password": "पासवर्ड बदलें",
    "Current Password": "वर्तमान पासवर्ड",
    "New Password": "नया पासवर्ड",
    "Confirm Password": "पासवर्ड की पुष्टि करें",
    "Update Password": "पासवर्ड अपडेट करें",
    "Language & Region": "भाषा और क्षेत्र",
    "Language": "भाषा",
    "Date Format": "दिनांक प्रारूप",
    "Time Zone": "समय क्षेत्र",
    "Save Preferences": "प्राथमिकताएं सहेजें",
    "AI & Analysis": "AI और विश्लेषण",
    "Analysis Mode": "विश्लेषण मोड",
    "Contradiction Strictness": "विरोधाभास सख्ती",
    "Save Settings": "सेटिंग्स सहेजें",
    "Email Notifications": "ईमेल सूचनाएं",
    "Save Notifications": "सूचनाएं सहेजें",
    "Manage your account, preferences and application settings.": "अपना खाता, प्राथमिकताएं और एप्लिकेशन सेटिंग्स प्रबंधित करें।",
    "Analysis Completed": "विश्लेषण पूरा हुआ",
    "Receive email when analysis is completed": "विश्लेषण पूरा होने पर ईमेल प्राप्त करें",
    "Risk Alerts": "जोखिम अलर्ट",
    "Receive email for high risk issues": "उच्च जोखिम वाले मुद्दों के लिए ईमेल प्राप्त करें",
    "Report Generated": "रिपोर्ट जनरेट की गई",
    "Receive email when reports are generated": "रिपोर्ट जनरेट होने पर ईमेल प्राप्त करें",
    "System Updates": "सिस्टम अपडेट",
    "Important updates and announcements": "महत्वपूर्ण अपडेट और घोषणाएं"
  },
  French: {
    "Dashboard": "Tableau de Bord",
    "Upload Contracts": "Télécharger des Contrats",
    "Analysis Results": "Résultats d'Analyse",
    "Reports": "Rapports",
    "Saved Reports": "Rapports Enregistrés",
    "Risk Overview": "Aperçu des Risques",
    "Clause Explorer": "Explorateur de Clauses",
    "Settings": "Paramètres",
    "Logout": "Déconnexion",
    "AI Legal Assistant": "Assistant Juridique IA",
    "Ask questions about your contracts and get AI insights.": "Posez des questions sur vos contrats et obtenez des informations de l'IA.",
    "Go to Assistant": "Aller à l'Assistant",
    "Profile Information": "Informations de Profil",
    "Your Name": "Votre Nom",
    "Full Name": "Nom Complet",
    "Email Address": "Adresse E-mail",
    "Phone Number": "Numéro de Téléphone",
    "Company": "Entreprise",
    "Role": "Rôle",
    "Bio": "Biographie",
    "Save Changes": "Enregistrer les Modifications",
    "Appearance": "Apparence",
    "Theme": "Thème",
    "Light": "Clair",
    "Dark": "Sombre",
    "System": "Système",
    "Primary Color": "Couleur Principale",
    "Your data is secure": "Vos données sont sécurisées",
    "All data is encrypted and stored securely.": "Toutes les données sont cryptées et stockées en toute sécurité.",
    "Change Password": "Changer le Mot de Passe",
    "Current Password": "Mot de Passe Actuel",
    "New Password": "Nouveau Mot de Passe",
    "Confirm Password": "Confirmer le Mot de Passe",
    "Update Password": "Mettre à Jour",
    "Language & Region": "Langue et Région",
    "Language": "Langue",
    "Date Format": "Format de Date",
    "Time Zone": "Fuseau Horaire",
    "Save Preferences": "Enregistrer les Préférences",
    "AI & Analysis": "IA et Analyse",
    "Analysis Mode": "Mode d'Analyse",
    "Contradiction Strictness": "Rigueur de Contradiction",
    "Save Settings": "Enregistrer les Paramètres",
    "Email Notifications": "Notifications par E-mail",
    "Save Notifications": "Enregistrer les Notifications",
    "Manage your account, preferences and application settings.": "Gérez votre compte, vos préférences et les paramètres de l'application.",
    "Analysis Completed": "Analyse terminée",
    "Receive email when analysis is completed": "Recevoir un e-mail lorsque l'analyse est terminée",
    "Risk Alerts": "Alertes de risque",
    "Receive email for high risk issues": "Recevoir un e-mail pour les problèmes à haut risque",
    "Report Generated": "Rapport généré",
    "Receive email when reports are generated": "Recevoir un e-mail lorsque les rapports sont générés",
    "System Updates": "Mises à jour du système",
    "Important updates and announcements": "Mises à jour et annonces importantes"
  },
  German: {
    "Dashboard": "Dashboard",
    "Upload Contracts": "Verträge Hochladen",
    "Analysis Results": "Analyseergebnisse",
    "Reports": "Berichte",
    "Saved Reports": "Gespeicherte Berichte",
    "Risk Overview": "Risikoübersicht",
    "Clause Explorer": "Klausel-Explorer",
    "Settings": "Einstellungen",
    "Logout": "Abmelden",
    "AI Legal Assistant": "KI Rechtsassistent",
    "Ask questions about your contracts and get AI insights.": "Stellen Sie Fragen zu Ihren Verträgen und erhalten Sie KI-Erkenntnisse.",
    "Go to Assistant": "Zum Assistenten",
    "Profile Information": "Profilinformationen",
    "Your Name": "Ihr Name",
    "Full Name": "Vollständiger Name",
    "Email Address": "E-Mail-Adresse",
    "Phone Number": "Telefonnummer",
    "Company": "Unternehmen",
    "Role": "Rolle",
    "Bio": "Biografie",
    "Save Changes": "Änderungen Speichern",
    "Appearance": "Erscheinungsbild",
    "Theme": "Design",
    "Light": "Hell",
    "Dark": "Dunkel",
    "System": "System",
    "Primary Color": "Primärfarbe",
    "Your data is secure": "Ihre Daten sind sicher",
    "All data is encrypted and stored securely.": "Alle Daten werden verschlüsselt und sicher gespeichert.",
    "Change Password": "Passwort Ändern",
    "Current Password": "Aktuelles Passwort",
    "New Password": "Neues Passwort",
    "Confirm Password": "Passwort Bestätigen",
    "Update Password": "Passwort Aktualisieren",
    "Language & Region": "Sprache & Region",
    "Language": "Sprache",
    "Date Format": "Datumsformat",
    "Time Zone": "Zeitzone",
    "Save Preferences": "Einstellungen Speichern",
    "AI & Analysis": "KI & Analyse",
    "Analysis Mode": "Analysemodus",
    "Contradiction Strictness": "Widerspruchs-Strenge",
    "Save Settings": "Einstellungen Speichern",
    "Email Notifications": "E-Mail-Benachrichtigungen",
    "Save Notifications": "Benachrichtigungen Speichern",
    "Manage your account, preferences and application settings.": "Verwalten Sie Ihr Konto, Ihre Einstellungen und Anwendungseinstellungen.",
    "Analysis Completed": "Analyse abgeschlossen",
    "Receive email when analysis is completed": "E-Mail erhalten, wenn die Analyse abgeschlossen ist",
    "Risk Alerts": "Risiko-Warnungen",
    "Receive email for high risk issues": "E-Mail für Hochrisikoprobleme erhalten",
    "Report Generated": "Bericht erstellt",
    "Receive email when reports are generated": "E-Mail erhalten, wenn Berichte erstellt werden",
    "System Updates": "System-Updates",
    "Important updates and announcements": "Wichtige Updates und Ankündigungen"
  },
  Spanish: {
    "Dashboard": "Panel de Control",
    "Upload Contracts": "Subir Contratos",
    "Analysis Results": "Resultados de Análisis",
    "Reports": "Informes",
    "Saved Reports": "Informes Guardados",
    "Risk Overview": "Resumen de Riesgos",
    "Clause Explorer": "Explorador de Cláusulas",
    "Settings": "Ajustes",
    "Logout": "Cerrar Sesión",
    "AI Legal Assistant": "Asistente Legal de IA",
    "Ask questions about your contracts and get AI insights.": "Haga preguntas sobre sus contratos y obtenga información de la IA.",
    "Go to Assistant": "Ir al Asistente",
    "Profile Information": "Información del Perfil",
    "Your Name": "Su Nombre",
    "Full Name": "Nombre Completo",
    "Email Address": "Dirección de Correo",
    "Phone Number": "Número de Teléfono",
    "Company": "Empresa",
    "Role": "Rol",
    "Bio": "Biografía",
    "Save Changes": "Guardar Cambios",
    "Appearance": "Apariencia",
    "Theme": "Tema",
    "Light": "Claro",
    "Dark": "Oscuro",
    "System": "Sistema",
    "Primary Color": "Color Primario",
    "Your data is secure": "Sus datos están seguros",
    "All data is encrypted and stored securely.": "Todos los datos están encriptados y almacenados de forma segura.",
    "Change Password": "Cambiar Contraseña",
    "Current Password": "Contraseña Actual",
    "New Password": "Nueva Contraseña",
    "Confirm Password": "Confirmar Contraseña",
    "Update Password": "Actualizar Contraseña",
    "Language & Region": "Idioma y Región",
    "Language": "Idioma",
    "Date Format": "Formato de Fecha",
    "Time Zone": "Zona Horaria",
    "Save Preferences": "Guardar Preferencias",
    "AI & Analysis": "IA y Análisis",
    "Analysis Mode": "Modo de Análisis",
    "Contradiction Strictness": "Rigor de Contradicción",
    "Save Settings": "Guardar Ajustes",
    "Email Notifications": "Notificaciones de Correo",
    "Save Notifications": "Guardar Notificaciones",
    "Manage your account, preferences and application settings.": "Administre su cuenta, preferencias y ajustes de la aplicación.",
    "Analysis Completed": "Análisis completado",
    "Receive email when analysis is completed": "Recibir un correo electrónico cuando se complete el análisis",
    "Risk Alerts": "Alertas de riesgo",
    "Receive email for high risk issues": "Recibir correo electrónico para problemas de alto riesgo",
    "Report Generated": "Informe generado",
    "Receive email when reports are generated": "Recibir un correo electrónico cuando se generen informes",
    "System Updates": "Actualizaciones del sistema",
    "Important updates and announcements": "Actualizaciones y anuncios importantes"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  // Sync with localStorage prefs if it exists
  const [language, setLanguageState] = useState(() => {
    try {
      const prefs = JSON.parse(localStorage.getItem("settings_prefs") || "null");
      return prefs?.language || "English";
    } catch {
      return "English";
    }
  });

  // Keep localStorage prefs in sync if language changes from anywhere
  const setLanguage = (newLang) => {
    setLanguageState(newLang);
    try {
      const prefs = JSON.parse(localStorage.getItem("settings_prefs") || "{}");
      prefs.language = newLang;
      localStorage.setItem("settings_prefs", JSON.stringify(prefs));
    } catch (e) {
      console.error(e);
    }
  };

  // The translation function
  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}
